modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="create__automation"
version="0.1.1"
displayName="Create: Automation"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-automation"
authors="vano201911"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create__automation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



